### ISSUE TITLE
Config flow could not be loaded: undefined

### ISSUE THREAD

**Issue by JaydenE55** [sysofwan/ha-triones#15]
I attempted to install the integration, but each time I am presented with "Config flow could not be loaded: undefined". I have my Bluetooth dongle passed through, but the integration still throws that error when trying to add it
![ha](https://user-images.githubusercontent.com/62227803/176982410-3b8fdce5-8663-4c50-beba-0b6b7f96726c.png)
.

**Comment by lyfesaver74** [comment]
I have this same issue

**Comment by biosniper** [comment]
I had this issue also but I am running with a supervised install of HA on Debian. The issue was the base OS didnt have Bluez installed, installed it and thats solved now so I imagine your installs for whatever reason do not have access to the BT module/device.

I'd suggest in order to troubleshoot properly you'll need to enable [debugging](https://github.com/sysofwan/ha-triones#debugging) for the plugin first and post the debug logs from it and list what type of install you are running and hardware :)

**Comment by lyfesaver74** [comment]
> 

Thank you so much, @biosniper for replying :D I am really interested in getting this to work.

I was under the impression pyBluez was installed with the HA install but I did add it to the Debian 11.3 host again and it installed.

I then tried the install/configuration steps again and hit the same issue. My looger does give the following information, tho:
Logger: aiohttp.server
Source: custom_components/triones/triones.py:13
Integration: Triones ([documentation](https://github.com/sysofwan/ha-triones), [issues](https://github.com/sysofwan/ha-triones/issues))
First occurred: 5:52:25 PM (2 occurrences)
Last logged: 5:53:13 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 145, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 222, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 249, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/triones/config_flow.py", line 37, in async_step_user
    devices = await discover()
  File "/config/custom_components/triones/triones.py", line 13, in discover
    devices = await BleakScanner.discover()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 99, in discover
    async with cls(**kwargs) as scanner:
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 79, in __aenter__
    await self.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 145, in start
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.NotReady] Resource Not Ready

**Comment by lyfesaver74** [comment]
Same results with a USB BT device

**Comment by lyfesaver74** [comment]
I should also add I am on Debian 11.3 with a Supervised HA install

**Comment by lyfesaver74** [comment]
![image](https://user-images.githubusercontent.com/61745478/179021345-8473f221-f8fd-4afa-97d5-a67d3acaaf48.png)

Just showing the radios are being reported in the CLI

**Comment by lyfesaver74** [comment]
Got it working! thanks so much. Just needed to get BT working 100% on the host first
