### ISSUE TITLE
Unable to connect to triones.

### ISSUE THREAD

**Issue by bartek810** [sysofwan/ha-triones#18]
Hey. I can not connect to my Triones device. I tried with a used one but also with a fresh one out of the box with same result: 
![image](https://user-images.githubusercontent.com/70979941/184705905-bbe5ae51-00ed-4bae-bcf9-de37bc90e823.png)

DEBUG: 
```
022-08-15 21:25:41.896 ERROR (MainThread) [custom_components.triones] Error getting status: [org.bluez.Error.InProgress] Operation already in progress
2022-08-15 21:25:41.900 DEBUG (MainThread) [custom_components.triones] Traceback (most recent call last):
  File "/config/custom_components/triones/triones.py", line 69, in update
    await self._device.connect(timeout=20)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 107, in connect
    device = await BleakScannerBlueZDBus.find_device_by_address(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 221, in find_device_by_address
    return await cls.find_device_by_filter(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 250, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 96, in __aenter__
    await self.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 137, in start
    self._stop = await manager.active_scan(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 405, in active_scan
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress

2022-08-15 21:25:41.901 DEBUG (MainThread) [custom_components.triones]  cc 23 33
2022-08-15 21:25:44.377 ERROR (MainThread) [custom_components.triones] Error getting status: [org.bluez.Error.InProgress] Operation already in progress
2022-08-15 21:25:44.467 DEBUG (MainThread) [custom_components.triones] Traceback (most recent call last):
  File "/config/custom_components/triones/triones.py", line 69, in update
    await self._device.connect(timeout=20)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 107, in connect
    device = await BleakScannerBlueZDBus.find_device_by_address(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 221, in find_device_by_address
    return await cls.find_device_by_filter(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 250, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 96, in __aenter__
    await self.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 137, in start
    self._stop = await manager.active_scan(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 405, in active_scan
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress

2022-08-15 21:25:44.468 DEBUG (MainThread) [custom_components.triones]  cc 23 33
```

**Comment by dave-code-ruiz** [comment]
newest HA have bluetooth integration, if you configure it, you cannot conect to legacy bluetooth integrations

https://www.home-assistant.io/integrations/bluetooth

If you delete bluetooth integration and restart you can now config ha-triones  bluetooth integrations again.
