### ISSUE TITLE
Unable to connect to QHM led strip

### ISSUE THREAD

**Issue by stelizap99** [sysofwan/ha-triones#21]
Hello! I have an HappyLighting RGB Strip that gets recognized in bluetooth as QHM-F439.
The script didn’t pull the address automatically so I had to get it manually.
I get an error named “Unknown error occured”.
The log says:

2022-09-18 15:39:39.788 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration candy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experienc>
2022-09-18 15:39:39.791 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration triones which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experie>
2022-09-18 15:39:39.792 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience>
2022-09-18 15:40:09.151 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that attempted to call BleakClient with an address instead of a BLEDevice. Please report issue to the custom integration author for triones >
2022-09-18 15:40:09.158 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 178, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/triones/config_flow.py", line 89, in async_step_manual
    return await self.async_step_validate()
  File "/config/custom_components/triones/config_flow.py", line 67, in async_step_validate
    error = await self.toggle_light()
  File "/config/custom_components/triones/config_flow.py", line 101, in toggle_light
    self.triones_instance = TrionesInstance(self.mac)
  File "/config/custom_components/triones/triones.py", line 26, in __init__
    self._device = BleakClient(self._mac)
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/models.py", line 207, in __init__
    raise BleakError(f"No device found for address {address_or_ble_device}")
bleak.exc.BleakError: No device found for address 12:18:11:00:F4:39
Is there a chance that my strip is not supported?

These are my UUID-s:
00001800-0000-1000-8000-00805f9b34fb
0000ffd5-0000-1000-8000-00805f9b34fb
0000ffd0-0000-1000-8000-00805f9b34fb

**Comment by stelizap99** [comment]
Heyyy, it was a bluetooth modem problem, got it fixed!
