### ISSUE TITLE
Cannot Connect to Light

### ISSUE THREAD

**Issue by Colorado4Wheeler** [sysofwan/ha-triones#3]
I also detailed this on your announcement post on HASS forums.

The light gets detected but then when you select the light it refuses to connect to it and add it to HA.

```2021-11-21 16:17:40 DEBUG (MainThread) [custom_components.triones] Discovered devices: [{'address': 'FF:FF:38:5B:40:65', 'name': 'Triones-FFFF385B4065'}, {'address': '50:32:37:8E:C0:9E', 'name': '50-32-37-8E-C0-9E'}, {'address': '7D:6E:88:67:D6:AC', 'name': '7D-6E-88-67-D6-AC'}, {'address': '13:76:96:07:E7:91', 'name': '13-76-96-07-E7-91'}, {'address': '4D:1D:50:98:F2:0D', 'name': '4D-1D-50-98-F2-0D'}, {'address': '02:C4:7F:51:2A:12', 'name': '02-C4-7F-51-2A-12'}, {'address': '5F:7C:40:A7:72:4A', 'name': '5F-7C-40-A7-72-4A'}, {'address': '79:D1:87:7F:9D:FD', 'name': '79-D1-87-7F-9D-FD'}, {'address': '5A:A6:8A:38:BF:20', 'name': '5A-A6-8A-38-BF-20'}, {'address': '49:42:DB:44:28:CD', 'name': '49-42-DB-44-28-CD'}, {'address': '30:EC:0C:04:EB:B2', 'name': '30-EC-0C-04-EB-B2'}, {'address': '74:E2:1F:75:69:E8', 'name': '74-E2-1F-75-69-E8'}, {'address': '61:2B:E7:F0:29:66', 'name': '61-2B-E7-F0-29-66'}]
2021-11-21 16:17:52 ERROR (MainThread) [custom_components.triones] Error getting status: Characteristic with UUID 0000ffd4-0000-1000-8000-00805f9b34fb could not be found!
2021-11-21 16:17:52 DEBUG (MainThread) [custom_components.triones] Traceback (most recent call last):
  File "/config/custom_components/triones/triones.py", line 73, in update
    await self._device.start_notify(R_CHARACTERISTIC_UUID, create_status_callback(future))
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 915, in start_notify
    raise BleakError(
bleak.exc.BleakError: Characteristic with UUID 0000ffd4-0000-1000-8000-00805f9b34fb could not be found!

2021-11-21 16:17:52 DEBUG (MainThread) [custom_components.triones]  cc 23 33
```

**Comment by sysofwan** [comment]
Thanks for reporting and the helpful error log. I have an idea on fixing this, but it might take some time. I assumed that the characteristic UUID is the same for all Triones. Apparently not so the implementation needs to query for the characteristics UUIDs first.

**Comment by sysofwan** [comment]
I did more digging into this. I think the implementation correctly follows [this protocol](https://github.com/madhead/saberlight/blob/master/protocols/Triones/protocol.md).

It is possible that your device is using a different UUIDs. Can you connect to your device using a BLE debug app and see the service and characteristic UUID it exposes?

**Comment by sysofwan** [comment]
Found more characteristic UUIDs from another open source [Triones implementation](https://github.com/pedasmith/BluetoothDeviceController/blob/5c6154794b9799d666448b24f57b2adf8ea60359/BluetoothDeviceController/BluetoothProtocols/Triones_LedLights_Custom.cs).

Do try the latest code if it fixes the issue. Otherwise, I will need you to do BLE scanning of your device the find the necessary UUIDs.

**Comment by claudiocn** [comment]
```
This error originated from a custom integration.

Logger: custom_components.triones
Source: custom_components/triones/triones.py:101
Integration: Triones (documentation, issues)
First occurred: 15:06:06 (3 occurrences)
Last logged: 15:06:13

Error getting status: [org.bluez.Error.Failed] Software caused connection abort
```

Have the same problem, too. 
To give some context, it was this one: https://pt.aliexpress.com/item/33002886875.html

**Comment by sysofwan** [comment]
@claudiocn this looks like a different error. Please [enable debugging](https://github.com/sysofwan/ha-triones#debugging) for full error trace.

**Comment by claudiocn** [comment]
here it is:
`2021-12-08 16:27:49 ERROR (MainThread) [custom_components.triones] Error getting status: [org.bluez.Error.Failed] Software caused connection abort
2021-12-08 16:27:49 DEBUG (MainThread) [custom_components.triones] Traceback (most recent call last):
File "/home/homeassistant/.homeassistant/custom_components/triones/triones.py", line 69, in update
await self._device.connect(timeout=20)
File "/srv/homeassistant/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 278, in connect
assert_reply(reply)
File "/srv/homeassistant/lib/python3.9/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Software caused connection abort
2021-12-08 16:27:49 DEBUG (MainThread) [custom_components.triones] cc 23 33`

**Comment by claudiocn** [comment]
Seems to be a timeout, don't know why :\

**Comment by sysofwan** [comment]
@claudiocn this is common. See [this issue](https://github.com/sysofwan/ha-triones/issues/5). It is a BLE connection issue that will self recover. The debug log “cc 23 e3” shows that it successfully recovered and sent a BLE message.

I will make an update to the logs to make it clearer.

**Comment by claudiocn** [comment]
But the problem is: it doesn't connect at all when setupping.

Just to give a try, tested with the following tool and it worked perfectly: https://github.com/vinceroti/bt-triones

**Comment by claudiocn** [comment]
Disconnected from the other library. Didn't work.
Turned it off and on again. Didn't work. Retried a couple of times and nothing.

```
2021-12-08 17:05:57 ERROR (MainThread) [custom_components.triones] No supported read/write UUIDs found
2021-12-08 17:05:57 DEBUG (MainThread) [custom_components.triones] cc 23 33
2021-12-08 17:06:06 ERROR (MainThread) [custom_components.triones] No supported read/write UUIDs found
2021-12-08 17:06:06 DEBUG (MainThread) [custom_components.triones] cc 23 33
2021-12-08 17:06:13 ERROR (MainThread) [custom_components.triones] No supported read/write UUIDs found
2021-12-08 17:06:13 DEBUG (MainThread) [custom_components.triones] cc 23 33
2021-12-08 17:07:12 ERROR (MainThread) [custom_components.triones] Error getting status: Device with address FF:FF:CD:02:EE:19 could not be found. Try increasing `timeout` value or moving the device closer.
2021-12-08 17:07:12 DEBUG (MainThread) [custom_components.triones] Traceback (most recent call last):
File "/home/homeassistant/.homeassistant/custom_components/triones/triones.py", line 69, in update
await self._device.connect(timeout=20)
File "/srv/homeassistant/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 216, in connect
raise BleakError(
bleak.exc.BleakError: Device with address FF:FF:CD:02:EE:19 could not be found. Try increasing `timeout` value or moving the device closer.
2021-12-08 17:07:12 DEBUG (MainThread) [custom_components.triones] cc 23 33
```

**Comment by sysofwan** [comment]
Thanks, this is have better logs and is the same issue here. `No supported read/write UUIDs found` means that the read UUID for your device is not known. Unfortunately, Triones uses many different UUIDs.

The test tool you used will only do writes to your device, but not reads (it does not know the current device state). The missing UUID here is for reads.

Can you help do this:

> It is possible that your device is using different UUIDs. Can you connect to your device using a BLE debug app (such as [this](https://play.google.com/store/apps/details?id=com.macdom.ble.blescanner)) and share the service and characteristic UUID it exposes?

**Comment by claudiocn** [comment]
![image](https://user-images.githubusercontent.com/1122214/145255023-f565b930-0bc1-4d29-b49c-d4922fe96eef.png)

**Comment by claudiocn** [comment]
From what I see, it's doing a match, it's a known UUID :\ 

![image](https://user-images.githubusercontent.com/1122214/145261709-c0c225ef-98f7-4232-a2f2-20b6c844e3f8.png)

**Comment by sysofwan** [comment]
Yeah, it’s weird. I’ll add some more debug logs later to figure this out.

**Comment by claudiocn** [comment]
Well, using it directly through the `gatttool` tool, did the following commands and using the source code in the **bt-triones**  to get the values to be sent, did the following and it's working perfectly from the RPi from where I'm using Home Assistant:

- `gatttool -I` to start
- `connect FF:FF:CD:02:EE:19` to connect to the trione with that Mac Address
-  `primary` to see the actions (handle), the first one did nothing, but the second one (0x007) did! so with the **bt-triones** values...
- `char-write-cmd 0x007 cc2433` to turn off
- `char-write-cmd 0x007 cc2333` to turn on
- `char-write-cmd 0x007 5600ff0000f0aa` to change to colour: R=00, G=ff, B=00
![image](https://user-images.githubusercontent.com/1122214/145272178-e45f0bac-2cb6-4f1c-bb22-3e0721ddc815.png)

values come from here (from **bt-triones**  source code):
![image](https://user-images.githubusercontent.com/1122214/145271810-c86aedbc-c199-4567-9c7c-ee45bfebd1a7.png)
![image](https://user-images.githubusercontent.com/1122214/145271816-a8f6a46e-0466-4d6f-b5c8-994e1d35323a.png)
![image](https://user-images.githubusercontent.com/1122214/145272012-9037b856-13dd-4b87-8f3d-5884bda35ba0.png)

**Comment by sysofwan** [comment]
Can you add logs to the triones.py:72 uuid detection code to see why it’s not finding the uuid?

You can modify the code inside `custom_components/triones` folder.

**Comment by claudiocn** [comment]
It seems to be empty.

```
2021-12-08 20:00:01 INFO (MainThread) [custom_components.triones] {}
2021-12-08 20:00:01 ERROR (MainThread) [custom_components.triones] No supported read/write UUIDs found
2021-12-08 20:00:01 DEBUG (MainThread) [custom_components.triones] cc 23 33
```
![image](https://user-images.githubusercontent.com/1122214/145276121-7ed83550-1bdd-4d19-bd1d-3856588f6191.png)

**Comment by sysofwan** [comment]
Try logging `self._device.services.characteristics.values()` instead

**Comment by claudiocn** [comment]
```
                LOGGER.info(self._device)
                LOGGER.info(self._device.services)
                LOGGER.info(self._device.services.characteristics.values())
```

```
2021-12-08 20:06:01 INFO (MainThread) [custom_components.triones] BleakClientBlueZDBus, FF:FF:CD:02:EE:19
2021-12-08 20:06:01 INFO (MainThread) [custom_components.triones] <bleak.backends.service.BleakGATTServiceCollection object at 0x7f4a0c90d0>
2021-12-08 20:06:01 INFO (MainThread) [custom_components.triones] dict_values([])
```

**Comment by sysofwan** [comment]
Not sure why the library is not detecting any characteristics. You can check if it detects it if we go through each service. Sample code [here](https://github.com/hbldh/bleak/blob/develop/examples/service_explorer.py).

Meanwhile, you can hardcode the uuid in code too as a workaround.  Just set `self._write_uuid and `self._read_uuid` in the `__init__` method.

**Comment by claudiocn** [comment]
Did some digging with that sample code. the list of services is empty. Can't do a ".values()" but printing for each loop returns zero iterations. Really strange.

Probably because of that, even if I put the UUID, it doesn't work:
```
2021-12-08 20:59:23 DEBUG (MainThread) [custom_components.triones] Traceback (most recent call last):
File "/home/homeassistant/.homeassistant/custom_components/triones/triones.py", line 90, in update
await self._device.start_notify(self._read_uuid, create_status_callback(future))
File "/srv/homeassistant/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 915, in start_notify
raise BleakError(
bleak.exc.BleakError: Characteristic with UUID 0000ffd9-0000-1000-8000-00805f9b34fb could not be found!
2021-12-08 20:59:23 DEBUG (MainThread) [custom_components.triones] cc 23 33
```

**Comment by claudiocn** [comment]
Not sure if this is usefull, but here's some additional information:
```
pi@raspberrypi:~ $ gatttool -i hci0 -b FF:FF:CD:02:EE:19 --characteristics
Discover all characteristics failed: Request attribute has encountered an unlikely error
pi@raspberrypi:~ $ gatttool -i hci0 -b FF:FF:CD:02:EE:19 --primary
attr handle = 0x0001, end grp handle = 0x0004 uuid: 0000ffd0-0000-1000-8000-00805f9b34fb
attr handle = 0x0005, end grp handle = 0x0007 uuid: 0000ffd5-0000-1000-8000-00805f9b34fb
pi@raspberrypi:~ $ gatttool -i hci0 -b FF:FF:CD:02:EE:19 --char-read
A valid handle is required
pi@raspberrypi:~ $ gatttool -i hci0 -b FF:FF:CD:02:EE:19 --interactive
[FF:FF:CD:02:EE:19][LE]> exit
pi@raspberrypi:~ $ gatttool -i hci0 -b FF:FF:CD:02:EE:19 --char-desc
handle = 0x0001, uuid = 00002800-0000-1000-8000-00805f9b34fb
handle = 0x0002, uuid = 00002803-0000-1000-8000-00805f9b34fb
handle = 0x0003, uuid = 0000ffd4-0000-1000-8000-00805f9b34fb
handle = 0x0004, uuid = 00002902-0000-1000-8000-00805f9b34fb
handle = 0x0005, uuid = 00002800-0000-1000-8000-00805f9b34fb
handle = 0x0006, uuid = 00002803-0000-1000-8000-00805f9b34fb
handle = 0x0007, uuid = 0000ffd9-0000-1000-8000-00805f9b34fb
```

**Comment by sysofwan** [comment]
Another guess is we need to call `await self._device.get_services()` explicitly before querying the services in some implementation. Example [here](https://github.com/hbldh/bleak/blob/4adf5d5b6ef7dd2642b6e71a2fa4e913a85d077a/examples/connect_by_bledevice.py). Can you try it?

**Comment by wroblear** [comment]
the same problem, 
No supported read/write UUIDs found
I have changed UUIDs for that which I got in Bluetootk scanner app, the same, 
any idea?
I see that there is no new information since 12.2021,

**Comment by dave-code-ruiz** [comment]
I create supported code repository for uuid 0000fff3-0000-1000-8000-00805f9b34fb is elk-bledom strip.

https://github.com/dave-code-ruiz/elkbledom-ha
