### ISSUE TITLE
Error in triones.py:101

### ISSUE THREAD

**Issue by zohann** [sysofwan/ha-triones#5]
Logger: custom_components.triones
Source: custom_components/triones/triones.py:101
Integration: Triones (documentation, issues)
First occurred: 30.11.2021 г., 23:49:01 (64 occurrences)
Last logged: 18:46:30

2021-12-01 01:38:57 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 01:41:27 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 02:04:27 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 02:06:57 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 02:35:57 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 02:38:27 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 02:58:57 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 03:02:27 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 03:45:57 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 03:48:27 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 04:11:27 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 04:36:57 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 05:03:27 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 05:05:57 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 05:08:27 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-01 05:34:57 ERROR (MainThread) [custom_components.triones] Error getting status:

**Comment by sysofwan** [comment]
This is usually a BLE connection issue. It usually resolves itself. Unless you have specific issue, for example, the light state is not in sync in Home Assistant, I won't worry about it.

If you need further help, please include the [debug logs](https://github.com/sysofwan/ha-triones#debugging) with this bug.

**Comment by zohann** [comment]
`
[20211202.txt](https://github.com/sysofwan/ha-triones/files/7639592/20211202.txt)
`

**Comment by zohann** [comment]
This is the log before the update

**Comment by sysofwan** [comment]
Yes, it is coming from timeouts communicating to the device (there is a 30 second limit by Home Assistant). This usually self-recovers on the next update.

**Comment by zohann** [comment]
after the update, it also throws errors
2021-12-02 18:00:51 DEBUG (MainThread) [custom_components.triones] ef 01 77
2021-12-02 18:00:51 DEBUG (MainThread) [custom_components.triones] 66 e3 24 41 20 01 db db 00 00 03 99
2021-12-02 18:01:21 DEBUG (MainThread) [custom_components.triones] ef 01 77
2021-12-02 18:01:21 DEBUG (MainThread) [custom_components.triones] 66 e3 24 41 20 01 db db 00 00 03 99
2021-12-02 18:01:51 DEBUG (MainThread) [custom_components.triones] ef 01 77
2021-12-02 18:01:51 DEBUG (MainThread) [custom_components.triones] 66 e3 24 41 20 01 db db 00 00 03 99
2021-12-02 18:02:21 DEBUG (MainThread) [custom_components.triones] ef 01 77
2021-12-02 18:02:21 DEBUG (MainThread) [custom_components.triones] 66 e3 24 41 20 01 db db 00 00 03 99
2021-12-02 18:02:51 DEBUG (MainThread) [custom_components.triones] ef 01 77
2021-12-02 18:02:56 ERROR (MainThread) [custom_components.triones] Error getting status:
2021-12-02 18:02:56 DEBUG (MainThread) [custom_components.triones] Traceback (most recent call last):
File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
fut.result()
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/triones/triones.py", line 90, in update
await asyncio.wait_for(future, 5.0)
File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2021-12-02 18:03:21 DEBUG (MainThread) [custom_components.triones] ef 01 77
2021-12-02 18:03:21 DEBUG (MainThread) [custom_components.triones] 66 e3 24 41 20 01 db db 00 00 03 99
2021-12-02 18:03:51 DEBUG (MainThread) [custom_components.triones] ef 01 77
2021-12-02 18:03:51 DEBUG (MainThread) [custom_components.triones] 66 e3 24 41 20 01 db db 00 00 03 99
2021-12-02 18:04:21 DEBUG (MainThread) [custom_components.triones] ef 01 77
2021-12-02 18:04:21 DEBUG (MainThread) [custom_components.triones] 66 e3 24 41 20 01 db db 00 00 03 99
2021-12-02 18:04:51 DEBUG (MainThread) [custom_components.triones] ef 01 77
2021-12-02 18:04:51 DEBUG (MainThread) [custom_components.triones] 66 e3 24 41 20 01 db db 00 00 03 99
2021-12-02 18:05:21 DEBUG (MainThread) [custom_components.triones] ef 01 77
2021-12-02 18:05:21 DEBUG (MainThread) [custom_components.triones] 66 e3 24 41 20 01 db db 00 00 03 99
2021-12-02 18:05:51 DEBUG (MainThread) [custom_components.triones] ef 01 77
2021-12-02 18:05:51 DEBUG (MainThread) [custom_components.triones] 66 e3 24 41 20 01 db db 00 00 03 99
2021-12-02 18:06:21 DEBUG (MainThread) [custom_components.triones] ef 01 77
2021-12-02 18:06:21 DEBUG (MainThread) [custom_components.triones] 66 e3 24 41 20 01 db db 00 00 03 99
